# Config file for automatic testing at travis-ci.org

sudo: required
language: python

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

matrix:
    include:
      - python: 3.6
        env: TOX_ENV=py36
      - python: 3.6
        env: TOX_ENV=flake8

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
